name: esp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.0.0
  flutter_blue_plus: ^1.32.4
  flutter_launcher_icons:
  permission_handler: ^11.0.0 # Add a valid version
  flutter_bluetooth_serial: 0.4.0 # Add a valid version
  animate_do: ^2.0.0 # Add a valid version
  shared_preferences:
  location:
  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration for flutter_native_splash
flutter_native_splash:
  color: "#FAF9F6"  # ✅ Light background color (e.g., off-white)
  image: assets/images/submark2.png
  color_dark: "#FAF9F6"  # ✅ Ensure dark mode also uses light color

  android_12:
    image: assets/images/submark2.png
    icon_background_color: "#FAF9F6"
    image_dark: assets/images/submark2.png
    icon_background_color_dark: "#FAF9F6"

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center
  fullscreen: true